In [1]:
import numpy as np

In [3]:
# Scalars
s = np.array(5)
print(s)

5


In [4]:
s.shape

()

In [5]:
x = s+3
print(x)

8


In [6]:
x.shape

()

In [7]:
# Vectors
v = np.array([1,2,3])
print(v)

[1 2 3]


In [8]:
v.shape

(3,)

In [9]:
print(v[1])

2


In [10]:
print(v[1:])

[2 3]


In [11]:
# Matrices
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m.shape

(3, 3)

In [13]:
print(m[1][2])

6


In [16]:
# Tensors
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


In [17]:
t.shape

(3, 3, 2, 1)

In [18]:
print(t[2][1][1][0])

16


In [19]:
# Changing Shapes
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [20]:
v.shape

(4,)

In [24]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [27]:
print(v[None,:])

[[1 2 3 4]]


In [28]:
print(v[:, None])

[[1]
 [2]
 [3]
 [4]]


In [29]:
# Element-wise operations - Suppose you had a list of numbers, and you wanted to add 5 to every item in the list
# Without NumPy
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i]+=5

In [30]:
print(values)

[6, 7, 8, 9, 10]


In [31]:
# With NumPy
values = [1,2,3,4,5]
print(np.array(values)+5)

[ 6  7  8  9 10]


In [33]:
print(np.add(values,5))

[ 6  7  8  9 10]


In [34]:
print(np.multiply(values,5))

[ 5 10 15 20 25]


In [35]:
print(np.array(values)*5)

[ 5 10 15 20 25]


In [37]:
m *= 0
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
print(a+b)

[[ 3  7]
 [11 15]]


In [39]:
print(np.add(a,b))

[[ 3  7]
 [11 15]]


In [40]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])

In [41]:
print(a+c)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [42]:
# NumPy Matrix Multiplication
m = np.array([[1,2,3],[4,5,6]])
n = m*0.25

In [43]:
n.shape

(2, 3)

In [44]:
m.shape

(2, 3)

In [45]:
print(n)

[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]


In [46]:
print(m*n)

[[0.25 1.   2.25]
 [4.   6.25 9.  ]]


In [47]:
print(np.multiply(m,n))

[[0.25 1.   2.25]
 [4.   6.25 9.  ]]


In [48]:
# Matrix Product
a = np.array([[1,2,3,4],[5,6,7,8]])

In [49]:
a.shape

(2, 4)

In [50]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [51]:
b.shape

(4, 3)

In [52]:
print(np.matmul(a,b))

[[ 70  80  90]
 [158 184 210]]


In [53]:
print(np.dot(a,b))

[[ 70  80  90]
 [158 184 210]]


In [54]:
print(np.matmul(b,a))

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [55]:
# Transpose
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m.shape

(3, 4)

In [56]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
m_t = m.T
m_t[3][1]=200
print(m_t)

[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]


In [58]:
inputs = np.array([[-0.27, 0.45, 0.64, 0.31]])
print(inputs)

[[-0.27  0.45  0.64  0.31]]


In [59]:
inputs.shape

(1, 4)

In [60]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print(weights)

[[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]


In [61]:
weights.shape

(3, 4)

In [62]:
print(np.matmul(inputs, weights))

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [63]:
print(np.matmul(inputs, weights.T))

[[-0.01299  0.00664  0.13494]]


In [64]:
print(np.matmul(weights, inputs.T))

[[-0.01299]
 [ 0.00664]
 [ 0.13494]]


In [ ]:
# NumPy Quiz
def prepare_inputs(inputs):
    input_array = np.array([inputs])
    inputs_minus_min = input_array - np.min(input_array)
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)
    return input_array, inputs_minus_min, inputs_div_max

def multiply_inputs(m1,m2):
    if m1.shape[0]!=m2.shape[1] and m1.shape[1]!=m2.shape[2]:
        return False
    
    if m1.shape[1]==m2.shape[0]:
        return np.matmul(m1,m2)
    else:
        return np.matmul(m2,m1)
    
def find_mean(values):
    return np.mean(values)

input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))